# Copyright (c) Facebook, Inc. and its affiliates. All Rights Reserved

MODEL:
  TYPE: efficientnet_lite0_block_ds
  NAME: efficientnet_lite0_block_ds

  # DROP_RATE: 0.2
  # DROP_PATH_RATE: 0.2

  LABEL_SMOOTHING: 0.1

EVAL_MODE: False

TRAIN:
  EPOCHS: 180
  WEIGHT_DECAY: 1e-5
  BASE_LR: 0.1
  LR_SCHEDULER:
    NAME: 'cosine'

AUG:
  AUTO_AUGMENT: 'rand-m5-mstd0.5-inc1'
  # MIXUP: 0.
  # REPROB: 0.

DS:
  PRETRAINED: ""

  DISTILL: False
  DISTILL_WEIGHT: 0.7
  DISTILL_FEATURE: False
  DISTILL_FEATURE_WEIGHT: 1e-3

  ACT_FUN: 'learnable_relu6_hard'
  KEEP_ALL_ACT: False
  ACT_FROM_LIST: False
  ACT_LIST: []

  ACT_FROM_SEARCH: False
  SEARCH_CKPT: ""

  DECAY_SLOPE: False
  DECAY_MODE: 'iter'
  START_EPOCH: 0
  END_EPOCH: 0

  START_SLOPE: 0
  END_SLOPE: 1

  SEARCH: True
  L0_SPARSITY: 0.4

  ADD_FINAL_ACT: 'relu6'

  LAT_BEFORE: [0,42.85,89.55,63.13,42.59,35.58,17.11,16.53,16.53,19.42,28.17,28.17,15.95,14.54,14.54,14.54,14.3,0]
  
  LAT_AFTER: [0,24.7,4.03,5.16,8.58,10.37,2.16,2.3,2.3,4.7,5.78,5.78,7.68,12.7,12.7,12.7,3.02,0]
